import type { SystemArchitecture } from "@/types/system"
import type { ThreatAnalysisResult, Severity } from "@/types/threat"
import type { GitHubExportData } from "@/types/export"
import { COMPONENT_TYPE_LABELS } from "@/types/system"

const SEVERITY_EMOJI: Record<Severity, string> = {
  critical: "🔴",
  high: "🟠",
  medium: "🟡",
  low: "🟢",
}

export function generateGitHubReport(
  system: SystemArchitecture,
  analysis: ThreatAnalysisResult
): GitHubExportData {
  const lines: string[] = []
  const riskLevel =
    analysis.riskScore.overall >= 75 ? "Critical" :
    analysis.riskScore.overall >= 50 ? "High" :
    analysis.riskScore.overall >= 25 ? "Medium" : "Low"

  lines.push(`# 🛡️ AI Threat Model Report: ${system.name}`)
  lines.push("")
  lines.push(`> Generated by AI Threat Modeler on ${new Date(analysis.analyzedAt).toLocaleDateString()}`)
  lines.push("")
  lines.push(`## Risk Score: ${analysis.riskScore.overall}/100 (${riskLevel})`)
  lines.push("")

  // Summary table
  lines.push("| Metric | Value |")
  lines.push("|--------|-------|")
  lines.push(`| Total Threats | ${analysis.threats.length} |`)
  lines.push(`| ${SEVERITY_EMOJI.critical} Critical | ${analysis.riskScore.bySeverity.critical} |`)
  lines.push(`| ${SEVERITY_EMOJI.high} High | ${analysis.riskScore.bySeverity.high} |`)
  lines.push(`| ${SEVERITY_EMOJI.medium} Medium | ${analysis.riskScore.bySeverity.medium} |`)
  lines.push(`| ${SEVERITY_EMOJI.low} Low | ${analysis.riskScore.bySeverity.low} |`)
  lines.push(`| Frameworks | OWASP LLM Top 10, STRIDE, MITRE ATLAS |`)
  lines.push("")

  // System components table
  lines.push("## System Components")
  lines.push("")
  lines.push("| Component | Type | External-Facing | Technologies |")
  lines.push("|-----------|------|-----------------|--------------|")
  for (const c of system.components) {
    lines.push(
      `| ${c.name} | ${COMPONENT_TYPE_LABELS[c.type]} | ${c.isExternalFacing ? "⚠️ Yes" : "No"} | ${c.technologies.join(", ")} |`
    )
  }
  lines.push("")

  // Threats grouped by severity
  lines.push("## Identified Threats")
  lines.push("")

  const severities: Severity[] = ["critical", "high", "medium", "low"]
  for (const sev of severities) {
    const sevThreats = analysis.threats.filter((t) => t.severity === sev)
    if (sevThreats.length === 0) continue

    lines.push(`### ${SEVERITY_EMOJI[sev]} ${sev.charAt(0).toUpperCase() + sev.slice(1)}`)
    lines.push("")

    for (const threat of sevThreats) {
      lines.push(`#### ${threat.id.toUpperCase()}: ${threat.title}`)
      lines.push("")
      lines.push(`- **Severity:** ${sev.charAt(0).toUpperCase() + sev.slice(1)}`)
      lines.push(`- **Likelihood:** ${threat.likelihood}`)

      const compNames = threat.affectedComponentIds
        .map((id) => system.components.find((c) => c.id === id)?.name ?? id)
        .join(", ")
      lines.push(`- **Affected Components:** ${compNames}`)

      if (threat.owaspMappings.length > 0) {
        lines.push(`- **OWASP:** ${threat.owaspMappings.map((m) => `${m.id} - ${m.name}`).join(", ")}`)
      }
      if (threat.strideMappings.length > 0) {
        lines.push(`- **STRIDE:** ${threat.strideMappings.map((m) => m.category.replace(/-/g, " ")).join(", ")}`)
      }
      if (threat.atlasMappings.length > 0) {
        lines.push(`- **ATLAS:** ${threat.atlasMappings.map((m) => `${m.techniqueId ?? m.tacticId} - ${m.techniqueName ?? m.tacticName}`).join(", ")}`)
      }

      lines.push(`- **Attack Vector:** ${threat.attackVector}`)
      lines.push(`- **Impact:** ${threat.impact}`)
      lines.push("")

      if (threat.mitigations.length > 0) {
        lines.push("**Mitigations:**")
        for (const m of threat.mitigations) {
          lines.push(`  - ${m.title} (${m.effort} effort)`)
        }
        lines.push("")
      }
    }
  }

  // Mitigation checklist
  lines.push("## Mitigation Checklist")
  lines.push("")
  const allMitigations = analysis.threats.flatMap((t) =>
    t.mitigations.map((m) => ({ ...m, threatTitle: t.title }))
  )
  // Deduplicate by title
  const seen = new Set<string>()
  for (const m of allMitigations) {
    if (seen.has(m.title)) continue
    seen.add(m.title)
    lines.push(`- [ ] **[${m.priority.toUpperCase()}]** ${m.title}`)
  }
  lines.push("")

  lines.push("---")
  lines.push("*Generated by AI Threat Modeler — Powered by OWASP LLM Top 10, STRIDE, and MITRE ATLAS*")

  const markdown = lines.join("\n")
  const filename = `threat-model-${system.name.toLowerCase().replace(/\s+/g, "-")}.md`

  return { markdown, filename }
}
